version: b{build}
image: Visual Studio 2019
branches:
  only:
    - master
    - v5.0
environment:
  SHOPIFYSHARP_API_KEY:
    secure: uF/ZRFFV19rv9tyOtspau/SpzMLQaGFWgBYge7kRC4vk/HHRxKda7BaNi46QhzN/
  SHOPIFYSHARP_SECRET_KEY:
    secure: 36pbnnyMdnyPXqzIPVTMNzv8qAzEUs/f7LaheBMCsZHC7EO11llgiMPCwHPhtms4
  SHOPIFYSHARP_ACCESS_TOKEN:
    secure: Lt70HrGBrQwKIFWE13zFZRGGwRoPKi1VKjtqBzuR3rdz3w6zD1YXXXe/Zb7xaqX+
  SHOPIFYSHARP_MY_SHOPIFY_URL:
    secure: aWjxVhXImxXX98GcYDmAbGVDxZk9kRaMKGnhm0CLuJ0aFYs0OMNaJOqyT8S4sh9P
  NUGET_API_KEY:
    secure: 5pYXU7B8TPMjbBhtoK6uEZkv8hzhQgO4zGRV4wjbRmPoNZ4a9acMQpPBQu8+IuCK
build_script:
- ps: ./scripts/build.ps1
test_script:
- ps: ./scripts/test.ps1
deploy_script:
  - ps: ./scripts/deploy.ps1
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
    - appveyor.yml
