name: Build Pipeline

on:
  push:
    branches: [ master, setup-github-actions ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    environment: "Build Environment"

    steps:
    - name: Install fish
      run: sudo apt-get -qq update && sudo apt-get -qq install fish 

    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          3.1.x

    - name: Build and pack
      run: .github/scripts/build.fish
      shell: fish {0}
      env:
        GITHUB_RUN_NUMBER: "${{ github.run_number }}"

  test:
    name: "Unit tests"
    runs-on: ubuntu-20.04
    # Do not run this job until the build job completes
    needs: build
    environment: "Unit test environment"

    env:
      SHOPIFYSHARP_ACCESS_TOKEN: "${{ secrets.SHOPIFYSHARP_ACCESS_TOKEN }}"
      SHOPIFYSHARP_API_KEY: "${{ secrets.SHOPIFYSHARP_API_KEY }}"
      SHOPIFYSHARP_SECRET_KEY: "${{ secrets.SHOPIFYSHARP_SECRET_KEY }}"
      SHOPIFYSHARP_MY_SHOPIFY_URL: "${{ secrets.SHOPIFYSHARP_MY_SHOPIFY_URL }}"

    steps:
    - name: Checkout branch
      uses: actions/checkout@master

    - name: Execute unit test script
      run: scripts/test.ps1
      shell: pwsh

  publish:
    name: "Publish and release"
    runs-on: ubuntu-20.04
    needs: test
    environment: "Nuget deployment environment"

    steps:
    - name: Publish package to Nuget
      run: echo "would publish to nuget here. need to set up conditions so that only release tags are published." #dotnet nuget push */bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s "https://api.nuget.org/v3/index.json"

    - name: Create Github release
      run: echo "would create github release here"
